//
// Created by xgallom on 9/23/19.
//

#ifndef XLANG_ROOT_XLANGER_INCLUDE_XLANGER_PARSER_PARSER_H
#define XLANG_ROOT_XLANGER_INCLUDE_XLANGER_PARSER_PARSER_H

#include "Rule.h"

#endif //XLANG_ROOT_XLANGER_INCLUDE_XLANGER_PARSER_PARSER_H
